# -*- coding: utf-8 -*-
"""Bike_sharing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13hqKDEeezyGAgns_KPgKaKdIocvJCJ4H
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

data_day = pd.read_csv('https://raw.githubusercontent.com/HugoAmadeus/Submission/main/Dashboard/day.csv')
data_hour = pd.read_csv('')

data_bike = data_hour.merge(data_day, on='dteday', how='inner', suffixes=('_hour', '_day'))

weather_labels = {1: 'Jernih', 2: 'Kabut', 3: 'Curah Hujan Ringan', 4: 'Curah Hujan Lebat'}
data_bike['weather_label'] = data_bike['weathersit_day'].map(weather_labels)
data_bike['dteday'] = pd.to_datetime(data_bike['dteday'])
data_bike['season_day'] = data_bike.season_hour.astype('category')
data_bike['holiday_day'] = data_bike.holiday_hour.astype('category')

data_bike.rename(columns={"dteday": "date", "yr": "year", "mnth": "month", "weathersit": "weather",
                          "hum": "humidity", "cnt": "total_count"}, inplace=True)

st.title('Bike Rental Analysis Dashboard')

st.subheader('Penyewaan Sepeda pada Hari Libur')
avg_holiday = data_bike.groupby('holiday_day')['cnt_day'].mean().reset_index().sort_values("cnt_day")
plt.figure(figsize=(8, 5))
sns.barplot(x='holiday_day', y='cnt_day', data=avg_holiday, palette='Set2')
plt.title('Penyewaan Sepeda pada Hari Libur')
plt.xlabel('Hari Libur')
plt.ylabel('Rata-rata Penyewaan')
plt.xticks([0,1],['Tidak Libur','Libur'])
st.pyplot(plt)

st.subheader('Korelasi Suhu dengan Order Bike Riding')
plt.figure(figsize=(10,6))
sns.scatterplot(x='temp_day', y='cnt_day', data=data_bike, hue='season_day')
plt.xlabel("Temperature (degC)")
plt.ylabel("Total Rides")
plt.title("Clusters of bikeshare rides by season and temperature (2011-2012)")
plt.tight_layout()
st.pyplot(plt)

st.subheader('Conclusion')
st.write("""
- Hal ini dapat disebabkan oleh tingginya aktivitas transportasi pada hari-hari kerja ketika orang-orang bepergian ke pekerjaannya maupun pulang dari pekerjaannya. Kenaikan penyewaan sepeda pada hari-hari kerja kemungkinan cerminan dari kebutuhan orang-orang beraktivitas.
- Order sepeda memiliki nilai minimum saat winter. Namun seiring dengan meningkatnya temperatur, permintaan penyewaan sepeda memiliki tingkat nilai tertinggi pada saat summer.
""")
